name: til
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:
  repository_dispatch:
    types: [tick]
jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          YEAR=$(date -u +%Y)
          echo "$(date -u +'%Y-%m-%d %H:%M')" >> "${YEAR}.md"
          git config user.name  "zham"
          git config user.email "zhameersheraztampugao@gmail.com"
          git add "${YEAR}.md"
          git commit -m "${YEAR}: $(date -u +%H:%M)"
          git push
